
Turn 4
================================================================
error: communication error with bot: read failed, errno was: 0 (Success)
Last input received was:


Bot error output was:
Traceback (most recent call last):
  File "MyBot.py", line 58, in <module>
    command_queue.append(intendMove(ship, random.choice([ Direction.North, Direction.South, Direction.East, Direction.West ])))
  File "MyBot.py", line 24, in intendMove
    return false
NameError: name 'false' is not defined

