
Turn 2
================================================================
error: communication error with bot: read failed, errno was: 0 (Success)
Last input received was:


Bot error output was:
Traceback (most recent call last):
  File "MyBot.py", line 57, in <module>
    command_queue.append(intendMove(ship, random.choice([ Direction.North, Direction.South, Direction.East, Direction.West ])))
  File "MyBot.py", line 22, in intendMove
    logging.error(MapCell(ship.position.directional_offset(direction)).is_occupied)
TypeError: __init__() missing 1 required positional argument: 'halite_amount'

